### PR TITLE
WIP Add JobTask and add errorMessage to EngineJob

### PR DESCRIPTION
**Pull request by mpkocher**

### CODE REVIEW

**Comment by mpkocher** [comment]
@natechols and @skinner  Would you mind start reviewing this?

**Comment by natechols** [comment]
I see a few test coverage gaps but I can fill those in later when I write integration tests.  Otherwise LGTM.

**Comment by mpkocher** [comment]
@natechols What test coverage locations would you like to see improved?

**Comment by natechols** [comment]
Just unit tests for model changes, especially w.r.t. JSON serialization.  Of course the integration tests cover this implicitly, but every time I skip writing unit tests for the low-level functions I end up regretting it later.  Anyway, this doesn't need to be addressed immediately.

**Pull request merged**
