### PR TITLE
Add db test on startup

### PR DESCRIPTION
**Pull request by smcclellan7**

### CODE REVIEW

**Comment by smcclellan7** [comment]
@mpkocher how does this look?

**Comment by mpkocher** [comment]
If that future fails does that stop the system from starting up? Or does this system still startup?

**Comment by smcclellan7** [comment]
Hm, I'm fiddling around with it, and I can get the akka system to shutdown, but I can't figure out how to get the jvm to shutdown, if that's what you're looking for.  I could stick a System.exit call in there, but that feels ugly.  What do you think?

**Comment by mpkocher** [comment]
I would suggest making a call the JobsActor on startup and shutdown if that future fails. What do you think?

**Comment by mpkocher** [comment]
Can you test this model by starting up a fresh system, shutting it down, delete "uuid" from a table, then start the system up. It should fail to start up and return a non-zero exit code.

**Comment by smcclellan7** [comment]
This is working for me, i.e. failing when the db is in an inconsistent state, passing otherwise. I'm not crazy about having to force the system to exit like that, but if I just throw an exception, Akka tries to keep everything running and the exception never reaches the top.

**Comment by mpkocher** [comment]
https://github.com/PacificBiosciences/smrtflow/blob/master/smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala#L159

There's a hook on `start`. Make a call to `jobsDaoActor ? GetSummary` after the successful bind, then kill things at that level.

**Comment by mpkocher** [comment]
@smcclellan7 Can you update this?

**Comment by smcclellan7** [comment]
I can move the test to the startup() method, but what's the purpose of going through the Akka layer?

**Comment by mpkocher** [comment]
That works too. I was still think in terms of the old slick 2 model.

**Pull request merged**
