### PR TITLE
Correctly update collections

### PR DESCRIPTION
**Pull request by smcclellan7**

### CODE REVIEW

**Comment by mpkocher** [comment]
Please add a unittest

**Comment by smcclellan7** [comment]
Yeah, I'm trying to figure out how to do that.  There's already a unittest that I thought covered this; I'm not sure why it was passing.

**Comment by mpkocher** [comment]
Maybe just load Mark's XML and make sure you can parse it with your code? 

Those data models have everything as optional, I assume that's creating some friction.

**Comment by smcclellan7** [comment]
Yep, I can confirm that smrtlink fails on Mark's XML without these changes, but succeeds with them.

**Pull request merged**
