### PR TITLE
Add IdAble model to start to replace Either[Int, UUID]

### PR DESCRIPTION
**Pull request by mpkocher**
Added example as a test.

### CODE REVIEW

**Comment by natechols** [comment]
Will this automatically handle conversion to strings, e.g. when forming URLs in the client layer?

**Comment by mpkocher** [comment]
It's still boxed if you call toString.

```
import Models._; import ModelImplicits._
val i: IdAble = 1
val u: IdAble = UUID.randomUUID()
u.toString
i.toString
history
@ u.toString 
res11: String = "UUIDIdAble(1770b34b-4624-405f-85c1-04198b078586)"
@ i.toString 
res12: String = "IntIdAble(1)"
```

I think overriding toString might be a bit too heavy handed. 

A util func can do the conversion. 

```
@ def idableToString(i: IdAble): String = i match {case IntIdAble(x) => x.toString; case UUIDIdAble(u) => u.toString} 
defined function idableToString
@ idableToString(i) 
res18: String = "1"
@ idableToString(u) 
res19: String = "1770b34b-4624-405f-85c1-04198b078586"
@  

```

Any ideas?

**Comment by natechols** [comment]
For this to be most useful I think it needs to come with a built-in method - but we could name it something other than `toString` if there's a good reason not to override it.

**Comment by mpkocher** [comment]
Would `toUnboxedString` work? It's a bit verbose, but I'm blanking on a name for an alternative toString.

**Comment by natechols** [comment]
or `toIdString`, or `toSimpleString`, ... I don't have strong preferences.

**Comment by mpkocher** [comment]
@natechols Does this work for you?

**Comment by natechols** [comment]
LGTM

**Pull request merged**
