### PR TITLE
Add mock importing of data tool.

### PR DESCRIPTION
**Pull request by mpkocher**
It's runnable via 

sbt "smrt-server-link/run-main com.pacbio.secondary.smrtlink.tools.InsertMockData"

### CODE REVIEW

**Comment by mpkocher** [comment]
@skinner Can you tick the tires on this? Locally it takes ~230 sec to import. 

There's some room for improvement.

**Comment by mpkocher** [comment]
@skinner Can you merge this back if it looks like a reasonable start point?

**Comment by skinner** [comment]
I've run it a few times; I've seen it succeed, but I've also seen this:

```
[info] Ignoring commit()/close() fail: java.sql.SQLException: database in auto-commit mode
[error] Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[error] 	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[error] 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error] 	at scala.concurrent.Await$.result(package.scala:190)
[error] 	at com.pacbio.database.Database$$anonfun$run$1.apply(Database.scala:183)
[error] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[error] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

which seems to result in a hang.  That was running with a fresh database (deleted the db file before running).

I'm not sure what the deal is there; since it might just be another manifestation of our underlying DB issues, I'm inclined to merge this PR and see where we get with Jayson's DB changes.

**Comment by mpkocher** [comment]
If it's not working for you locally, the timeout might need to be increased.

**Pull request merged**
