### PR TITLE
started simulator testing of delete jobs, plus pbservice compatibility

### PR DESCRIPTION
**Pull request by natechols**
@mpkocher had to change `isActive` to `Optional[Boolean]` to keep pbservice from choking on older smrtlink instances

### CODE REVIEW

**Comment by mpkocher** [comment]
Is it possible to sort this out at the IO layer in the JSON protocol layer and default to true if isActive is not there? Currently, this backward compatibility motivation is resulting in database changes to support this, which doesn't sound right. 

The migration doesn't look consistent with the new definitions?

https://github.com/natechols/smrtflow/blob/ad3c4f0a8cfd9aaacd82deaae60ea100b2aba073/smrt-server-link/src/main/scala/db/migration/V19__JobDelete.scala#L15

https://github.com/natechols/smrtflow/blob/ad3c4f0a8cfd9aaacd82deaae60ea100b2aba073/smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala#L101

Is sqlite's type looseness the reason why there aren't errors?

It's also not clear what `isActive=None` is intended to mean.

**Comment by mpkocher** [comment]
I'm not sure what the default behavior of sqlite is, but I think one of these needs to have an explicit not null to be consistent with the slick table definition?

https://github.com/natechols/smrtflow/blob/ad3c4f0a8cfd9aaacd82deaae60ea100b2aba073/smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/database/TableModels.scala#L357

https://github.com/natechols/smrtflow/blob/ad3c4f0a8cfd9aaacd82deaae60ea100b2aba073/smrt-server-link/src/main/scala/db/migration/V19__JobDelete.scala#L16

**Comment by natechols** [comment]
Yes, we can sort this out at the IO layer, but that means writing a custom JSON protocol for the affected models.  I wasn't sure which model we preferred - the custom protocol will be gross but it would at least keep the rest of the code simpler, and we could potentially remove it in the future.  Should I take that approach?

My naive assumption was that using `Option[Boolean]` simply means that NULL values will be allowed.  This does seem like black magic to me.

**Comment by mpkocher** [comment]
I agree that this is not awesome to have to write custom spray JSON protocols. However, this might isolate the required changes. 

You bring up a good point. The client really won't strictly work with older versions (i.e., pbservice delete-job will fail on smrtlink-beta). Not sure how to handle this. When adding a new endpoint or changes to the public API (e.g., data models), it might be good to bump the smrtflow version. Perhaps in future versions we could require the client to check /status to get the version and fail early. if it's not compatible.

**Comment by natechols** [comment]
In principle I agree that we should enforce version compatibility in pbservice.  In practice, our internal users would freak out if we apply this universally.  Maybe just tag specific functionality like this as requiring a minimum version?

**Comment by natechols** [comment]
I will start over with a new branch.

**Pull request closed without merging**
